package com.occar.constant;

public interface CommonConstants {
	String TYPE_DOCUMENTS = "Documents";
	String SUCCESS = "success";
	String FAILURE = "failure";
	String TRIP_OPERATION_DRIVER_START = "TRIP_OPERATION_DRIVER_START";
	String TRIP_OPERATION_PASSENGER_START = "TRIP_OPERATION_PASSENGER_START";
	String TRIP_OPERATION_PASSENGER_JOIN = "TRIP_OPERATION_PASSENGER_JOIN";
	String DEFAULT_VEHICLE_ATTR = "DEFAULT_VEHICLE";
	String ATTR_PERSON_ACTIVE = "PERSON_ACTIVE";
	String GOOGLE_CAR_STOP_NAME = "GOOGLE_CAR_STOP_NAME";
	String GOOGLE_API_KEY = "AIzaSyB0Qp5bV34_DfNQk5L9o5b2vVMcT0wrAg4";
}
